name: actionexam

on:
  push:
    # branches: [ main ]
    # paths:
    #   - src/**
  pull_request:
    branches: [ main ]
    paths:
      - src/**

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   name: Lint con Flake 8
  #   steps:
  #     - name: Check out source repository
  #       uses: actions/checkout@v3
  #     - name: Set up Python environment
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.11"
  #     - name: flake8 Lint
  #       uses: py-actions/flake8@v2

  build:
    name: Docker
    runs-on: ubuntu-latest
    # needs: Lint
    steps:
      - uses: actions/checkout@v2
          
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DH_USUARIO }}
          password: ${{ secrets.DH_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true 
          tags: ${{ secrets.DH_USUARIO }}/fastapi:latest
 
  aws:
    name: Deploy image to aws
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AMZ_IP }}
        username: ${{ secrets.AMZ_USUARIO }}
        key: ${{ secrets.AMZ_CLAVE }}
        port: 22  # ${{ secrets.PORT }}
        script: |
            sleep 40
            docker stop web && docker rm web
            docker rmi rafarota/fastapi
            docker run -d -p 80:8000 --name web rafarota/fastapi
  
  # health_check_job:
  #   runs-on: ubuntu-latest
  #   name: Check for status 200 and title text "lokerse.dev"
  #   needs: aws
  #   steps:
  #     - uses: actions/checkout@v2
  #     - id: test
  #       uses: johnlokerse/website-healthcheck@v2
  #       with:
  #         web-url: "http://54.152.179.147"
  #         scan-for-text: "Ejemplo Flask App"